name: build-nix-on-droid
on:
  workflow_dispatch:
jobs:
  build-nix-on-droid:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@main
      - uses: ./.github/actions/install-nix
      - uses: cachix/cachix-action@master
        with:
          name: ${{ secrets.CACHIX_NAME }}
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: rm -f ~/.config/nix/nix.conf
      - run: |
          nix flake update
          sed -i '/users\.users\.nix-on-droid\.shell = lib.getExe pkgs\.fish;/a users.users.nix-on-droid.uid = lib.mkForce 10377;' nix-on-droid.nix
          sed -i '/users\.users\.nix-on-droid\.shell = lib.getExe pkgs\.fish;/a users.groups.nix-on-droid.gid = lib.mkForce 10377;' nix-on-droid.nix
          nix build --verbose --print-build-logs --impure --print-out-paths .#nixosConfigurations.default.config.system.build.toplevel
